services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    dns:
      - 8.8.8.8
      - 1.1.1.1
    command: npm run dev
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - backend
    command: npm run dev
